### ISSUE TITLE
Using rewrk in a benchmarking project 

### ISSUE THREAD

**Issue by waghanza** [ChillFish8/rewrk#42]
Hi,

I'm leading an OSS benchmarking project, https://github.com/the-benchmarker/web-frameworks.

We currently use `wrk` to compute our results.

As I can see in this project documentation, the full http 1 and 2 specs are followed here, in contrary of `wrk`. 

Could you point me were `wrk` does not follow http 1.1 specs ?

Regards,

**Comment by ChillFish8** [comment]
Hello, 

It's not that it does not follow the spec, it's that it uses a part of the spec that just isn't used much nowadays, to be specific, HTTP pipelining. All modern browsers have this feature disabled now along with a lot of proxies, because it was too difficult to get servers to play nicely with one another using the feature. 

HTTP/2 basically entirely replaces pipelining now and also avoids most of the issues pipelining had.

So it's not a spec issue, it's just rewrk chooses to not pipeline requests because most of the time servers aren't actually pipelining requests in the real world, so it can lead to some servers having inflated numbers with pipelining enabled. Still, it is technically part of the spec, so it is valid to benchmark using pipelining, rewrk just chooses not to which can give some *slightly* more realistic numbers, but we all know for the most part that the numbers generated by these tools are often miles higher than what an actual real-world implementation would handle.

**Comment by waghanza** [comment]
> All modern browsers have this feature disabled now

You mean that wrk implements pipelining on the client side ? I mean I can use wrk on servers that aren't pipelining any http requests

**Comment by ChillFish8** [comment]
> You mean that wrk implements pipelining on the client side? I mean I can use wrk on servers that aren't pipelining any HTTP requests

If a server doesn't support pipelining then there is no effect, a good demo of the differences pipelining can have on benchmarking is something like Python's `Japronto` vs `Uvicorn` since Japronto supports pipelining and Uvicorn does not, their results are massively different.

**Comment by waghanza** [comment]
Thanks for the clarification. I'll try to use rewrk to try benchmarking with http2
